#!/bin/bash

unset MAKEFLAGS

monoexec=

if [ ! -z "$CDN_RAWC" ]; then
	binary="$(which $CDN_RAWC)"
else
	binary=$srcdir/../bin/Debug/cdn-rawc.exe
	monoexec=mono
fi

if [ ! -f "$binary" ];
then
	binary=$srcdir/../bin/Release/cdn-rawc.exe
fi

if [ ! -f "$binary" ];
then
	echo "Could not find cdnrawc.exe binary to run tests"
	exit 1
fi

for f in $files; do
	$monoexec "$binary" --validate -q "$srcdir/$f"
	status=$?

	if [ $status -ne 0 ]; then
		exit $status
	fi
done
