#!/bin/bash

unset MAKEFLAGS

monoexec=

if [ $(uname) == "Darwin" ]; then
	mono_framework_path="/Library/Frameworks/Mono.framework/Versions/Current"
	codyn_framework_path="/Library/Frameworks/Codyn.framework/Resources/mono"

	if [ -d "$mono_framework_path" ]; then
        export DYLD_FALLBACK_LIBRARY_PATH="$mono_framework_path/lib:$codyn_framework_path/lib:$DYLD_FALLBACK_LIBRARY_PATH:/usr/lib:/usr/local/lib"
	fi
fi

if [ ! -z "$CDN_RAWC" ]; then
	binary="$(which $CDN_RAWC)"
else
	binary=$srcdir/../bin/Debug/cdn-rawc.exe
	monoexec=mono
fi

if [ ! -f "$binary" ];
then
	binary=$srcdir/../bin/Release/cdn-rawc.exe
fi

if [ ! -f "$binary" ];
then
	echo "Could not find cdnrawc.exe binary to run tests"
	exit 1
fi

for f in $files; do
	$monoexec "$binary" --validate -q "$srcdir/$f"
	status=$?

	if [ $status -ne 0 ]; then
		exit $status
	fi
done
