#!/bin/bash

unset MAKEFLAGS

binary=$srcdir/../bin/Debug/cdn-rawc.exe

if [ ! -f "$binary" ];
then
	binary=$srcdir/../bin/Release/cdn-rawc.exe
fi

if [ ! -f "$binary" ];
then
	echo "Could not find cdnrawc.exe binary to run tests"
	exit 1
fi

for f in $files; do
	mono "$binary" --validate -q "$srcdir/$f"
	status=$?

	if [ $status -ne 0 ]; then
		exit $status
	fi
done
